[package]
name = "robot_catrina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.8.0"
serialport = "4.2.2"
soloud = "1.0.5"
